# Generated by Django 2.1 on 2019-03-21 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Offer title')),
                ('description', models.TextField(verbose_name='Apply description')),
                ('date', models.DateTimeField(blank=True)),
                ('status', models.CharField(choices=[('PE', 'PENDING'), ('AC', 'ACEPTED'), ('RE', 'REJECTED')], max_length=8, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='DataScientist_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
            ],
        ),
        migrations.AddField(
            model_name='apply_model',
            name='dataScientist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datame.DataScientist_model'),
        ),
    ]
