# Generated by Django 2.1 on 2019-03-23 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PE', 'PENDING'), ('AC', 'ACCEPTED'), ('RE', 'REJECTED')], max_length=8, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Offer_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Offer title')),
                ('description', models.TextField(verbose_name='Offer description')),
                ('price_offered', models.FloatField(verbose_name='Price offered')),
                ('currency', models.CharField(choices=[('0', '€'), ('1', '$'), ('2', '£')], max_length=1, verbose_name='Currency type')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('limit_time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
