# Generated by Django 2.1 on 2019-03-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(blank=True)),
                ('limit_date', models.DateTimeField(blank=True)),
                ('expiration', models.IntegerField()),
                ('dataScientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datame.DataScientist_model')),
            ],
        ),
        migrations.CreateModel(
            name='Offer_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Offer title')),
                ('description', models.TextField(verbose_name='Offer description')),
                ('price_offered', models.FloatField(verbose_name='Price offered')),
                ('currency', models.CharField(choices=[('0', '\\c280'), ('1', '$'), ('2', '\\c2a3')], max_length=1, verbose_name='Currency type')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('limit_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='apply_model',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Apply title'),
        ),
        migrations.AddField(
            model_name='contract_model',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datame.Offer_model'),
        ),
    ]
