# Generated by Django 2.1 on 2019-03-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0002_auto_20190324_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='accepted_company',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='accepted_ds',
            field=models.BooleanField(default=False),
        ),
    ]
