# Generated by Django 2.1 on 2019-03-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0002_auto_20190321_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_model',
            name='currency',
            field=models.CharField(choices=[('0', '€'), ('1', '$'), ('2', 'U+00A3')], max_length=1, verbose_name='Currency type'),
        ),
    ]
