# Generated by Django 2.1.7 on 2019-03-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='moment',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
