# Generated by Django 2.1 on 2019-03-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0002_auto_20190325_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='company',
        ),
        migrations.AddField(
            model_name='contract',
            name='apply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datame.Apply'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='contract',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='datame.Contract'),
        ),
    ]
