# Generated by Django 2.1 on 2019-03-21 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0003_auto_20190321_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('path', models.CharField(max_length=200, verbose_name='Path')),
                ('apply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datame.Apply_model')),
            ],
        ),
        migrations.AlterField(
            model_name='offer_model',
            name='currency',
            field=models.CharField(choices=[('0', '€'), ('1', '$'), ('2', '£')], max_length=1, verbose_name='Currency type'),
        ),
        migrations.AddField(
            model_name='file_model',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datame.Offer_model'),
        ),
    ]
