# Generated by Django 2.1.7 on 2019-03-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datame', '0005_offer_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='contract',
            field=models.TextField(default='this is contract', verbose_name='Contract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='files',
            field=models.URLField(default='text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(verbose_name='Logo URL'),
        ),
    ]
